sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t pyoya1123/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true pyoya1123/docker-react-app npm run test -- --coverage

after_success:
  - ehco "Test success "